apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rk-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx-example
  rules:
    - http:
        paths:
        - path: /
          backend:
            serviceName: rk-api-service
            servicePort: 8080