apiVersion: apps/v1
kind: Deployment
metadata:
  name: rk-api
  labels:
    app: rk-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rk-api
  template:
    metadata:
      labels:
        app: rk-api
    spec:
      containers:
        - name: rk-api
          image: rk_api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: DEMO_REDIS_ADDR
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: queue_uri
            - name: DEMO_REDIS_PWD
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: redis_pwd
            - name: DEMO_REDIS_DB
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: redis_db
            - name: DEMO_REDIS_QUEUE_KEY
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: redis_queue_key
            - name: DEMO_KAFKA_MODE
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: kafka_mode
---
apiVersion: v1
kind: Service
metadata:
  name: rk-api-service
spec:
  selector:
    app: rk-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
