apiVersion: apps/v1
kind: Deployment
metadata:
  name: rk-worker
  labels:
    app: rk-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rk-worker
  template:
    metadata:
      labels:
        app: rk-worker
    spec:
      containers:
        - name: rk-worker
          image: rk_worker:latest
          imagePullPolicy: Never
          env:
            - name: REDIS_ADDR
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: queue_uri
            - name: REDIS_PWD
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: redis_pwd
            - name: REDIS_DB
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: redis_db
            - name: REDIS_QUEUE_KEY
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: redis_queue_key
            - name: KAFKA_MODE
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: kafka_mode